/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import control.hogwartsstudentsSQL;
import java.util.ArrayList;
import model.*;
/**
 *
 * @author Patrick Leaton
 */
public class HouseInfo extends javax.swing.JFrame {

    /**
     * Creates new form HouseInfo
     */
    public HouseInfo() {
        initComponents();
    }
    
    public HouseInfo(String house_name){
        initComponents();
        hogwartsstudents = new hogwartsstudentsSQL();
        fillFields(house_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        LabelHouseName = new java.awt.Label();
        LabelFounder = new java.awt.Label();
        LabelHouseGem = new java.awt.Label();
        LabelAnimal = new java.awt.Label();
        LabelElement = new java.awt.Label();
        LabelGosht = new java.awt.Label();
        ButtonGryffindor = new java.awt.Button();
        ButtonSlytherin = new java.awt.Button();
        ButtonRavenclaw = new java.awt.Button();
        ButtonHufflepuff = new java.awt.Button();
        TextHouseName = new java.awt.TextField();
        TextFounder = new java.awt.TextField();
        TextHouseGem = new java.awt.TextField();
        TextAnimal = new java.awt.TextField();
        TextElement = new java.awt.TextField();
        TextGhost = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label1.setText("House Information");

        LabelHouseName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelHouseName.setText("House Name:");

        LabelFounder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelFounder.setText("Founder:");

        LabelHouseGem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelHouseGem.setText("House Gem:");

        LabelAnimal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelAnimal.setText("Mascot:");

        LabelElement.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelElement.setText("Element:");

        LabelGosht.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelGosht.setText("Ghost:");

        ButtonGryffindor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonGryffindor.setLabel("Gryffindor");
        ButtonGryffindor.setName(""); // NOI18N
        ButtonGryffindor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGryffindorActionPerformed(evt);
            }
        });

        ButtonSlytherin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonSlytherin.setLabel("Slytherin");
        ButtonSlytherin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSlytherinActionPerformed(evt);
            }
        });

        ButtonRavenclaw.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonRavenclaw.setLabel("Ravenclaw");
        ButtonRavenclaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRavenclawActionPerformed(evt);
            }
        });

        ButtonHufflepuff.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonHufflepuff.setLabel("Hufflepuff");
        ButtonHufflepuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHufflepuffActionPerformed(evt);
            }
        });

        TextHouseName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TextFounder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TextHouseGem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TextAnimal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TextElement.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TextGhost.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonGryffindor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFounder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHouseGem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelGosht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonSlytherin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(ButtonRavenclaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(ButtonHufflepuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextHouseName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(TextFounder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextHouseGem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextElement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextGhost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonGryffindor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSlytherin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRavenclaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHufflepuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addComponent(LabelFounder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(TextFounder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelHouseGem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextHouseGem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(LabelAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(TextAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(LabelElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelGosht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextGhost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(TextElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGryffindorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGryffindorActionPerformed
        fillFields(ButtonGryffindor.getLabel());
    }//GEN-LAST:event_ButtonGryffindorActionPerformed

    private void ButtonSlytherinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSlytherinActionPerformed
        fillFields(ButtonSlytherin.getLabel());
    }//GEN-LAST:event_ButtonSlytherinActionPerformed

    private void ButtonRavenclawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRavenclawActionPerformed
        fillFields(ButtonRavenclaw.getLabel());
    }//GEN-LAST:event_ButtonRavenclawActionPerformed

    private void ButtonHufflepuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHufflepuffActionPerformed
        fillFields(ButtonHufflepuff.getLabel());
    }//GEN-LAST:event_ButtonHufflepuffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HouseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HouseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HouseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HouseInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HouseInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ButtonGryffindor;
    private java.awt.Button ButtonHufflepuff;
    private java.awt.Button ButtonRavenclaw;
    private java.awt.Button ButtonSlytherin;
    private java.awt.Label LabelAnimal;
    private java.awt.Label LabelElement;
    private java.awt.Label LabelFounder;
    private java.awt.Label LabelGosht;
    private java.awt.Label LabelHouseGem;
    private java.awt.Label LabelHouseName;
    private java.awt.TextField TextAnimal;
    private java.awt.TextField TextElement;
    private java.awt.TextField TextFounder;
    private java.awt.TextField TextGhost;
    private java.awt.TextField TextHouseGem;
    private java.awt.TextField TextHouseName;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
    private hogwartsstudentsSQL hogwartsstudents = new hogwartsstudentsSQL();
    private int StudentNames[];
    
    /**
     * This method will pull the information from the database using getHouseDetail() from the hogwartsstudentsSQL file. 
     * Then it will write that data to the text fields on the page.
     * @param house_name 
     */
    private void fillFields(String house_name) {
        HouseDetail house = hogwartsstudents.getHouseDetail(house_name);
        TextHouseName.setText(house.getHouse_name());
        TextFounder.setText(house.getFounder());
        TextHouseGem.setText(house.getHouse_gem());
        TextAnimal.setText(house.getAnimal());
        TextElement.setText(house.getElement());
        TextGhost.setText(house.getGhost());
    }
}
